trigger:
  branches:
    include:
    - main
  paths:
    include:
    - WeatherApi/**

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'WeatherApi/WeatherApi.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/publish'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/publish'
    artifactName: 'weatherapi'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureServiceConnection'
    appName: 'grpc-weather-client'
    appType: 'webAppLinux'
    package: '$(Build.ArtifactStagingDirectory)/publish'
