steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'WeatherApi/WeatherApi.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/WeatherApi'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/WeatherApi'
    artifactName: 'weatherapi'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureServiceConnection'
    appName: '<YOUR API APP SERVICE NAME>'
    appType: 'webAppLinux'
    package: '$(Build.ArtifactStagingDirectory)/WeatherApi'
